### ISSUE TITLE
Windows Chrome 下 多次换行出现的 bug

### ISSUE THREAD

**Issue by douseful** [okisdev/ChatChat#1]
当输入文本经过几次换行文本框高度超过屏幕之后，再进行输入屏幕会异常的上下滚动，如下图，继续输入就会出问题
![image](https://user-images.githubusercontent.com/52767905/227681620-aac20f49-6a3a-4f16-80a5-16129da22359.png)

**Comment by okisdev** [comment]
@douseful 

你好，感谢你的反馈，该问题已经在 1.1.8 解决。请刷新尝试一下，如果仍未解决，请告诉我，感谢你的使用！

**Comment by douseful** [comment]
> @douseful
> 
> 你好，感谢你的反馈，该问题已经在 1.1.8 解决。请刷新尝试一下，如果仍未解决，请告诉我，感谢你的使用！

还是有点小问题，邮件发了个视频给你…
