### ISSUE TITLE
Context mode for Claude Model

### ISSUE THREAD

**Issue by xubairp** [okisdev/ChatChat#126]
Hi,

 Currently there is limitation on context mode for Claude Model, the context doesnt work. Will you be able to add the context mode for Claude model. there were lots of feedback on the limitation of the Claude Documentation on implementation chat/context mode but with recent release from Vercel SDK for Claude chat implementation, i think thats fixed. it will be great to have this feature in ChatChat.

**Comment by okisdev** [comment]
supported in v0.1.0
