### ISSUE TITLE
问问题后加载一会并没有回应

### ISSUE THREAD

**Issue by HappyJiaJun** [okisdev/ChatChat#129]
![image](https://github.com/okisdev/ChatChat/assets/45360918/c22dd58e-9d6a-460a-8b25-a7ef012b7eb0)

**Comment by okisdev** [comment]
你好，麻烦提供一下使用的模型

**Comment by HappyJiaJun** [comment]
您好，应该是我的 api key 过期了，谢谢



---- 回复的原邮件 ----
| 发件人 | Harry ***@***.***> |
| 日期 | 2023年06月27日 13:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [okisdev/ChatChat] 问问题后加载一会并没有回应 (Issue #129) |

你好，麻烦提供一下使用的模型

**Comment by okisdev** [comment]
好的，那我关闭这个 issue 了
