### ISSUE TITLE
message rendering issues 

### ISSUE THREAD

**Issue by YangWang92** [okisdev/ChatChat#19]
Hi,
Thank you for sharing this interesting project. 

I encountered an issue where "\n\n" + "number" cannot be rendered properly. I appreciate your help in addressing this problem.

<img width="896" alt="image" src="https://user-images.githubusercontent.com/3883941/236099996-b0a425a1-022d-4535-af99-2b1b14c5d87b.png">

Thanks!
Yang

**Comment by okisdev** [comment]
Hi there, Could you provide more information regarding your conversation? 

I need more info such as *ServiceProvider*,  *Model*, if *Stream*, *Plugins* are turned on, and may require what question you asking for to identify the issue.

**Comment by okisdev** [comment]
Thank you for your report. This issue has now been resolved.
