### ISSUE TITLE
how to use origin FastChat API after depoly ChatChat?

### ISSUE THREAD

**Issue by JulyMin** [okisdev/ChatChat#199]
What parameters and scripts need to be modified to expose the original FastChat API (the one at /v1) after deploying ChatChat?

**Comment by okisdev** [comment]
Sorry, I'm not quite sure what you mean. there is no FastChat API embedded in ChatChat.

But if you have the same API structure as [OpenAI](https://platform.openai.com/docs/api-reference), then pretending it is an OpenAI API will work.

**Comment by JulyMin** [comment]
i was misunderstanding how it works. thank you for replying :)
