### ISSUE TITLE
本地用llama.cpp 部署的llm服务支持吗

### ISSUE THREAD

**Issue by shengkaixuan** [okisdev/ChatChat#2]
本地用llama.cpp 部署的llm服务，提供了与openai 兼容的API，chatchat 是否支持？？？？

**Comment by okisdev** [comment]
本地部署的需要测试一下，理论上是可以的。

**Comment by HelloEveryonehh** [comment]
@okisdev 想请问一下，本地部署LLM，只提供openai的api而不提供openai的api-key是允许的吗？

**Comment by okisdev** [comment]
> @okisdev 想请问一下，本地部署LLM，只提供openai的api而不提供openai的api-key是允许的吗？

本地部署你可以不填写 apiKey，选择 openai 但是只要是和 openai 一样的 api 接口就可以使用
