### ISSUE TITLE
Cannot switch to gpt-4-32k

### ISSUE THREAD

**Issue by YangWang92** [okisdev/ChatChat#20]
Hi, 
I got an error when I configure and switch to azure gpt-4-32k. I found that the server still use gpt-3.5-turbo instead of gpt-4-32k.

And I got the error when I refresh the webpage and start a new conversation.

> Unhandled Runtime Error
> Error: Text content does not match server-rendered HTML.
> 
> Warning: Text content did not match. Server: "gpt-3.5-turbo" Client: "gpt-4-32k"
> 
> See more info here: https://nextjs.org/docs/messages/react-hydration-error

<img width="926" alt="image" src="https://user-images.githubusercontent.com/3883941/236101790-3cc92a62-4c24-435e-9c5d-6e41d89e70df.png">

I have checked the gpt model:
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/3883941/236104063-a60cd3e0-5e16-49b7-ba37-fe8e4639fda2.png">

Thanks!

**Comment by okisdev** [comment]
麻烦提供一下在发送时请求，先进入 控制台 - 网络，然后发送一个请求（开启一段对话），找到 `/api/messages` 请求，查看一下以下内容，如果是 GPT4 ，那就是正确的

![CleanShot 2023-05-04 at 11 38 53@2x](https://user-images.githubusercontent.com/66008528/236181655-aeb5af9c-9207-4939-b3da-37f346bf8237.png)

**Comment by YangWang92** [comment]
I have confirmed that the request in the /api/messages is gpt-4, thanks a lot!
