### ISSUE TITLE
vercel部署需要设置环境变量吗？

### ISSUE THREAD

**Issue by Sean19899999** [okisdev/ChatChat#21]
如题，未设置环境变量部署后，打开vercel网页显示

Application error: a client-side exception has occurred (see the browser console for more information).
Digest: 908203380

不知道是不是没设置环境变量的原因！

**Comment by ieasyseek** [comment]
vercel部署必须设置环境变量 Postgresql 数据库你可以选择使用免费的Storage 如下图：
![微信图片_20230504114451](https://user-images.githubusercontent.com/78068033/236108363-3a369040-0f7e-4eb3-8f21-855a82c8e380.png)

**Comment by Sean19899999** [comment]
> vercel部署必须设置环境变量 Postgresql 数据库你可以选择使用免费的Storage 如下图： ![微信图片_20230504114451](https://user-images.githubusercontent.com/78068033/236108363-3a369040-0f7e-4eb3-8f21-855a82c8e380.png)

谢谢，请教如何使用免费的database？

**Comment by ieasyseek** [comment]
Storage 官网注册新建项目获取

**Comment by Sean19899999** [comment]
> Storage 官网注册新建项目获取

感谢感谢，没搞明白Storage的注册，最后用Railway的Postgresql数据库了，他家甚至可以直接和 vercel 搞 integration👍O(∩_∩)O

**Comment by ieasyseek** [comment]
搞定就可以

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Shuang Liang ***@***.***>
发送时间: Thursday, May 4, 2023 12:36:03 PM
收件人: okisdev/ChatChat ***@***.***>
抄送: ieasyseek ***@***.***>; Comment ***@***.***>
主题: Re: [okisdev/ChatChat] vercel部署需要设置环境变量吗？ (Issue #21)


Storage 官网注册新建项目获取

感谢感谢，没搞明白Storage的注册，最后用Railway的Postgresql数据库了，他家甚至可以直接和 vercel 搞 integration👍O(∩_∩)O
