### ISSUE TITLE
部署完成后配置了google搜索引擎还是无法连接到互联网

### ISSUE THREAD

**Issue by ieasyseek** [okisdev/ChatChat#22]
配置部署完成后并且配置了google网络搜索引擎，但是还是无法连接互联网获取内容。
![微信截图_20230504113911](https://user-images.githubusercontent.com/78068033/236108922-042e3188-a737-4a66-ab86-962edee27b8e.png)
![微信截图_20230504113820](https://user-images.githubusercontent.com/78068033/236108940-b315f3b4-4e51-4c65-bcea-086f9643dfe9.png)

**Comment by okisdev** [comment]
你好 请参考一下文档 https://docs.okis.dev/zh-CN/chat/features/search

**Comment by ieasyseek** [comment]
已经搞定 感谢

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Harry Yep ***@***.***>
发送时间: Thursday, May 4, 2023 6:16:47 PM
收件人: okisdev/ChatChat ***@***.***>
抄送: ieasyseek ***@***.***>; Author ***@***.***>
主题: Re: [okisdev/ChatChat] 部署完成后配置了google搜索引擎还是无法连接到互联网 (Issue #22)


你好 请参考一下文档 https://docs.okis.dev/zh-CN/chat/features/search

―
