### ISSUE TITLE
添加全局key

### ISSUE THREAD

**Issue by ShawnNotFound** [okisdev/ChatChat#267]
能否加一个配置全局key的地方，这样即使用户不登录也可以用我提供的key与特定的模型对话？

**Comment by okisdev** [comment]
OpenAI 可以全局使用 OPENAI_API_KEY

其他模型暂时不支持

**Comment by ShawnNotFound** [comment]
> OpenAI 可以全局使用 OPENAI_API_KEY
> 
> 其他模型暂时不支持

可以调整全局API的endpoint吗？

**Comment by okisdev** [comment]
暂时还不支持，但最近有重构计划

预计会支持以上功能，请问你需要哪个 API 的 Endpoint？

**Comment by ShawnNotFound** [comment]
> 暂时还不支持，但最近有重构计划
> 
> 预计会支持以上功能，请问你需要哪个 API 的 Endpoint？

在使用第三方的ChatGPT的endpoint，与OpenAI调用方法一致，我感觉可以直接像API一样做成可以自定义的环境变量

**Comment by okisdev** [comment]
你可以升级到 v0.0.67 设置全局的 OpenAI Endpoint，重构之后会支持更多 endpoint

**Comment by ShawnNotFound** [comment]
> 你可以升级到 v0.0.67 设置全局的 OpenAI Endpoint，重构之后会支持更多 endpoint

好的，谢谢
