### ISSUE TITLE
latex公式块重复输出

### ISSUE THREAD

**Issue by ShawnNotFound** [okisdev/ChatChat#268]
![Screenshot_20240315_084804_com.android.chrome.png](https://github.com/okisdev/ChatChat/assets/97796289/546aa60b-12d6-42ee-a919-0c70adeea532)

如图，在渲染到用$$包裹的公式块时会显示一次渲染过的和未渲染完全的内容
经测试，是渲染问题不是API返回内容问题（在开启渲染用户输入内容时，自己输入公式同样可出发此bug）

**Comment by okisdev** [comment]
感谢反馈，#270 已修复，更新 v0.0.68
