### ISSUE TITLE
v0.1.0遇到的问题

### ISSUE THREAD

**Issue by ShawnNotFound** [okisdev/ChatChat#292]
1. 电脑屏幕较宽时，设置页面显示不完全（看不到保存按钮），同时也无法下滑来解决问题
![image](https://github.com/okisdev/ChatChat/assets/97796289/da0425d8-099b-49b0-a5b3-4ec2918bcbed)

2. 在当前对话页面点击添加新对话无效

**Comment by okisdev** [comment]
Thanks.

Fixed in v[0.1.2](https://github.com/okisdev/ChatChat/releases/tag/0.1.2)
