### ISSUE TITLE
部署时环境变量填写方式

### ISSUE THREAD

**Issue by ShawnNotFound** [okisdev/ChatChat#302]
在使用railway部署时，所有模型的API和endpoint均为必填项（一共22个环境变量），但即使填写了所有环境变量，貌似也并不能直接使用，请问能否提供一个环境变量填写的指南或者范本？

**Comment by okisdev** [comment]
感谢反馈

Railway 部署忘记勾选环境变量为可选，现在已经修复这个问题，仅部署的话，无需填写任何环境变量。

针对 Railway 部署已经测试，直接通过 README 按钮可以直接部署。

具体的部署方法可以参考 https://docs.okis.dev/chat/intro
