### ISSUE TITLE
When will ChatChat support Azure OpenAI for Search particularly?

### ISSUE THREAD

**Issue by arunkumarakvr** [okisdev/ChatChat#327]
@okisdev 
- Do Azure OpenAI models support or work for Search particularly? 
- Do you have any released version that supports Azure OpenAI for Search particularly? 
- When are you going to make all the listed models support for Search particularly?

**Comment by okisdev** [comment]
Hi @arunkumarakvr, thanks for your interest in ChatChat.

Working hours may vary, so i may not response to any message over the weekend.

For Azure OpenAI, I currently have no plans to support it specifically, you can extend and proxy this type of AI provider support using Cloudflare AI or other platforms such as One-API.

A number of excellent open-source projects have been built on top of the search function, such as [Perplexica](https://github.com/ItzCrazyKns/Perplexica), [morphic](https://github.com/miurla/morphic), and others. You do can explore and enjoy them.

Your advice is utmost important for us, however, considering the different demand levels of users for the needs, we will not support all the needs at one time.

Currently, OpenAI is the only AI provider that supports search function on ChatChat. We might support more AI provider soon, but there is no specific timeframe.

Hope this helps.

Thanks, Harry
