### ISSUE TITLE
[Feature]新增自动语音回复

### ISSUE THREAD

**Issue by dgqyushen** [okisdev/ChatChat#51]
能否添加一个自动语言，每次ai回答完之后自动语音回复，另外添加代码高量与语音回复跳过代码？

**Comment by dgqyushen** [comment]
在要求gpt输出java代码的时候，右上角为unknown，无法高量，另外问下作者大大，有没有意愿让代码的颜色高亮再丰富点？

**Comment by okisdev** [comment]
有时候返回的内容确实没有代码语言，所以就设置变成了unknown
```
```python => ```[空的]
```

我研究一下有没有其他好看的颜色，替代一下目前这个
