### ISSUE TITLE
搜索引擎功能感觉不稳定

### ISSUE THREAD

**Issue by ccinoo** [okisdev/ChatChat#55]
您好：
    感觉搜索引擎功能不稳定，有时可以生效，有时又失效。入图中：

![image](https://github.com/okisdev/ChatChat/assets/30647119/fe484b9e-58b2-49a7-ba30-533919baf4d0)

**Comment by okisdev** [comment]
是用的 `/search Who is the president of the United States?`吗

**Comment by ccinoo** [comment]
> 是用的 `/search Who is the president of the United States?`吗

没错，必须的。

**Comment by okisdev** [comment]
好的 我研究一下

**Comment by okisdev** [comment]
fixed in v0.1.0
