### ISSUE TITLE
手机上无法登录

### ISSUE THREAD

**Issue by mwnu** [okisdev/ChatChat#61]
系统：安卓
版本：v0.0.7，Docker部署
浏览器：Edge，已关闭跟踪保护
问题：
手机上邮箱收到登录链接，可以跳转到：https://domain/zh-CN/profile/info看到登录状态，但是跳转到主页仍然显示未登录，无法使用Team Code。

**Comment by mwnu** [comment]
> 重新拉取一下 0.0.8 的代码，这个问题已经修复了

建议将镜像上传到Docker Hub，超过1G从ghcr.io拉取十分困难，试了好几次不成功。

**Comment by mwnu** [comment]
搞定了

**Comment by okisdev** [comment]
> > 重新拉取一下 0.0.8 的代码，这个问题已经修复了
> 
> 建议将镜像上传到Docker Hub，超过1G从ghcr.io拉取十分困难，试了好几次不成功。

已经发布到了 Docker Hub: https://hub.docker.com/r/okisdev/chatchat
