### ISSUE TITLE
无法打开新会话

### ISSUE THREAD

**Issue by mwnu** [okisdev/ChatChat#62]
无法连续对话，每次问都会从头开始；
无法创建新会话；
无法保存记录。
版本：v0.0.7，之前的版本没有这个问题，使用新版本并且使用Team之后就有了。

**Comment by okisdev** [comment]
可能是开启了“无上下文模式”，此模式下记录不会保存，也无法分享

**Comment by mwnu** [comment]
> 可能是开启了“无上下文模式”，此模式下记录不会保存，也无法分享
是这样的
