### ISSUE TITLE
Messages are not coming

### ISSUE THREAD

**Issue by Aceema** [okisdev/ChatChat#72]
Hello, when i try out the ai and say like hello or hi or anything else, it doesnt respond with anything.
![image](https://github.com/okisdev/ChatChat/assets/104942460/f88767bc-0713-42ad-b031-0799c70249c9)

**Comment by Aceema** [comment]
> Make sure you have setup the API key and other required info for specific service provide. :)

I have done everything but still not working

**Comment by okisdev** [comment]
which service provider are you using?
