### ISSUE TITLE
[bugs] env 设置没生效

### ISSUE THREAD

**Issue by CaoYunzhou** [okisdev/ChatChat#77]
![image](https://github.com/okisdev/ChatChat/assets/28099773/15494a59-6d95-47f4-a371-dcd534017ada)
![截图_选择区域_20230525184716](https://github.com/okisdev/ChatChat/assets/28099773/72b6e1e1-4f32-4f7f-93f7-168cc01f905a)

**Comment by CaoYunzhou** [comment]
也没有日志，是不是加一个日志开启info 或者err的功能？

**Comment by okisdev** [comment]
后期会把一些变量移到登陆后台里面，管理起来容易一些
