### ISSUE TITLE
本地拉下来运行的代码无法代理不生效，需要配置代理

### ISSUE THREAD

**Issue by nothing-byte** [okisdev/ChatChat#81]
如题，我本地部署以后，无法正常发送消息，出现了水合的错误Text content does not match server-rendered HTML.

**Comment by okisdev** [comment]
所有所需环境变量正确配置后，可以忽略这个错误

**Comment by nothing-byte** [comment]
好像还是没有用，我在本地项目运行的时候，与chat对话过程中出现了问题，出现了500错误 ，是我哪里没有配置对吗？
<img width="1098" alt="image" src="https://github.com/okisdev/ChatChat/assets/52440723/5ee0a73d-af45-4b51-a138-174495ea2854">
<img width="409" alt="image" src="https://github.com/okisdev/ChatChat/assets/52440723/8ff589b6-521b-4f3a-a962-b4cf834694c9">
这是我的环境变量
<img width="540" alt="image" src="https://github.com/okisdev/ChatChat/assets/52440723/b1fb8c06-50f2-462f-890e-5b6debf8eeda">

**Comment by okisdev** [comment]
拉取最新的代码，并尝试把 `.env.local` 换成 `.env`

**Comment by nothing-byte** [comment]
结果还是一样，是不是我本地代理需要作配置更新？

**Comment by okisdev** [comment]
https://github.com/okisdev/ChatChat/assets/66008528/15f9c3ff-de10-4d23-940d-deb75b56cef1

可以参考看看这个视频

**Comment by okisdev** [comment]
This question has been closed because no answer has been received for a long time.
