### ISSUE TITLE
File Chat - Option to disable default summary prompt

### ISSUE THREAD

**Issue by xubairp** [okisdev/ChatChat#91]
Hi, 
 How can we disable the default setting for the file chat, that will summarize the doc you upload. i am testing it with big text file and upon upload, i have to them wait longer for the file to generate summary which takes time and tokens which is not needed at all. I would prefer to have an option where i can just upload file and then i get some confirmation that file is upload and ready for QA.

Hope this can be done.

**Comment by okisdev** [comment]
Thanks for your feedback. This function is now supported.
